inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-5.5,5.9],[-6.7,5.4],[-4.7,5.3]]
  marching_cubes_bound: [[-5.5,5.9],[-6.7,5.4],[-4.7,5.3]]
data:
  input_folder: Datasets/Replica/office0
  output: output/Replica/office0
  # event folder
  event_folder: Datasets/replica_gt_png/office0
PoseGrid:
  zeropose_encoding: pretrained/office0_zeropose_encoding.npy
  startpose_encoding: pretrained/office0_startpose_encoding.npy
  boxing_scales: [0.35087719, 0.33057851, 0.4]