inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-5.0,4.6],[-4.4,6.9],[-2.8,3.1]]
  marching_cubes_bound: [[-5.0,4.6],[-4.4,6.9],[-2.8,3.1]]
data:
  input_folder: Datasets/Replica/office2
  output: output/Replica/office2
  # event folder
  event_folder: Datasets/replica_gt_png/office2
PoseGrid:
  zeropose_encoding: pretrained/office2_zeropose_encoding.npy
  boxing_scales: [0.41666667, 0.3539823, 0.6779661]