inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-5.3,6.5],[-5.1,6.0],[-4.5,5.2]]
  marching_cubes_bound: [[-5.3,6.5],[-5.1,6.0],[-4.5,5.2]]
data:
  input_folder: Datasets/Replica/office1
  output: output/Replica/office1
  # event folder
  event_folder: Datasets/replica_gt_png/office1
PoseGrid:
  zeropose_encoding: pretrained/office1_zeropose_encoding.npy
  startpose_encoding: pretrained/office1_startpose_encoding.npy
  boxing_scales: [0.33898305, 0.36036036, 0.41237113]