inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3.7,7.8],[-4.8,6.7],[-3.7,4.1]]
  marching_cubes_bound: [[-3.7,7.8],[-4.8,6.7],[-3.7,4.1]]
data:
  input_folder: Datasets/Replica/office4
  output: output/Replica/office4
  # event folder
  event_folder: Datasets/replica_gt_png/office4
PoseGrid:
  zeropose_encoding: pretrained/office4_zeropose_encoding.npy
  startpose_encoding: pretrained/office4_startpose_encoding.npy
  boxing_scales: [0.34782609, 0.34782609, 0.51282051]