inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-7.0,2.8],[-4.6,4.3],[-3.0,2.9]]
  marching_cubes_bound: [[-7.0,2.8],[-4.6,4.3],[-3.0,2.9]]
data:
  input_folder: Datasets/Replica/room1
  output: output/Replica/room1
  # event folder
  event_folder: Datasets/replica_gt_png/room1
PoseGrid:
  zeropose_encoding: pretrained/room1_zeropose_encoding.npy
  startpose_encoding: pretrained/room1_startpose_encoding.npy
  boxing_scales: [0.40816327, 0.4494382, 0.6779661]