inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-4.3,9.5],[-6.7,5.2],[-6.4,4.2]]
  marching_cubes_bound: [[-4.3,9.5],[-6.7,5.2],[-6.4,4.2]]
data:
  input_folder: Datasets/Replica/room2
  output: output/Replica/room2
  # event folder
  event_folder: Datasets/replica_gt_png/room2
PoseGrid:
  zeropose_encoding: pretrained/room2_zeropose_encoding.npy
  startpose_encoding: pretrained/room2_startpose_encoding.npy
  boxing_scales: [0.28985507, 0.33613445, 0.37735849]