inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
  marching_cubes_bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
data:
  input_folder: Datasets/Replica/room0
  output: output/Replica/room0
  # event folder
  # event_folder: Datasets/replica_gt_png/room0
  event_folder : Datasets/replica_gt_events/room0
PoseGrid:
  zeropose_encoding: pretrained/room0_zeropose_encoding.npy
  startpose_encoding: pretrained/room0_startpose_encoding.npy
  boxing_scales: [0.33898305, 0.45977011, 0.58823529]